### ISSUE TITLE
Preprocessor is caching modules

### ISSUE THREAD

**Issue by rolaveric** [guybedford/karma-systemjs-experiment#2]
Karma doesn't seem to be getting the updated file contents after changes for any files run through the preprocessor.
It knows a change occurred, so the event is going through, but the tests reload the exact same code without the changes.

I can replicate it using [rolaveric/ng1-to-ng2-example](https://github.com/rolaveric/ng1-to-ng2-example/tree/karma-systemjs-experiment) (with the preprocessor uncommented in `karma.conf.js`)
If I change `app/model/login.js` (a file going through the preprocessor) in a way that should break the test, it still passes. But if I change `app/model/login.spec.js`, the test picks up on the change.

**Comment by guybedford** [comment]
Thanks, I believe I've fixed this in https://github.com/systemjs/builder/commit/21b72386d7776d2f11f755219dc13da39a4b8ee9.

**Comment by rolaveric** [comment]
Nice. Confirmed fixed.
